name: test package installs

on: [push, pull_request]

jobs:
  test-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - ubi8
          - ubi9
    container: registry.access.redhat.com/${{ matrix.container }}:latest
    steps:
      - uses: actions/checkout@v4
      - name: test installation
        run: |
          yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-$(rpm -E '%{rhel}').noarch.rpm
          dnf copr enable -y ktdreyer/python3.11
          dnf -y install python3.11-dnf
